#+title: Eng102 Essay 5
#+date: [2024-10-30 Wed 00:00]
#+filetags: :english:
#+identifier: 20241030T000001

* Essay 5

** Topic

Social Media Addiction amongst Adolescents and Young Adults

/*/ Tags:

- social media
- addiction
- effects

** Sources

#+begin_quote
Zhu, Xinhong, et al. “Exploring Associations between Social Media Addiction, Social Media Fatigue, Fear of Missing out and Sleep Quality among University Students: A Cross-Section Study.” /PLoS ONE/, vol. 18, no. 10, Oct. 2023, pp. 1–12. /EBSCOhost/, https://doi.org/10.1371/journal.pone.0292429.
#+end_quote

#+begin_quote
https://web.archive.org/web/20240922165703/https://www.nytimes.com/2023/10/25/health/social-media-addiction.html
#+end_quote

#+begin_quote
Singh, Manpreet. “Examining the Relationship between Adolescent Self-Esteem and Social Media Addiction: A Comprehensive Study.” /Indian Journal of Health & Wellbeing/, vol. 15, no. 3, Sept. 2024, pp. 430–33. /EBSCOhost/, https://research.ebsco.com/linkprocessor/plink?id=2322278a-a11c-3c1e-9c48-746f43de3eab.
#+end_quote

#+begin_quote
Pitikoe-Chiloane, Moroesi G., and Hilda B. Dondolo. “Exploring How Far Fear of Missing Out and Self-Control Contribute to Social Media Addiction among TVET Students.” /International Journal of Health, Wellness & Society/, vol. 14, no. 2, June 2024, pp. 37–56. /EBSCOhost/, https://doi.org/10.18848/2156-8960/CGP/v14i02/37-56.
#+end_quote

#+begin_quote
Sujarwoto et al. “Social Media Addiction and Mental Health Among University Students During the COVID-19 Pandemic in Indonesia.” /International journal of mental health and addiction/ vol. 21,1 (2023): 96-110. doi:10.1007/s11469-021-00582-3
#+end_quote

#+begin_quote
Yang, Shang-Yu et al. “Does Smartphone Addiction, Social Media Addiction, and/or Internet Game Addiction Affect Adolescents' Interpersonal Interactions?.” /Healthcare (Basel, Switzerland)/ vol. 10,5 963. 23 May. 2022, doi:10.3390/healthcare10050963e
#+end_quote

#+begin_quote
Pellegrino, Alfonso et al. “Research trends in social media addiction and problematic social media use: A bibliometric analysis.” /Frontiers in psychiatry/ vol. 13 1017506. 10 Nov. 2022, doi:10.3389/fpsyt.2022.1017506
#+end_quote

#+begin_quote
Zhao, Jin et al. “Risk Factors Associated With Social Media Addiction: An Exploratory Study.” /Frontiers in psychology/ vol. 13 837766. 14 Apr. 2022, doi:10.3389/fpsyg.2022.837766
#+end_quote

#+begin_quote
Aydin, S.; Koçak, O.; Shaw, T.A.; Buber, B.; Akpinar, E.Z.; Younis, M.Z. Investigation of the Effect of Social Media Addiction on Adults with Depression. /Healthcare/ /2021/, /9/, 450. https://doi.org/10.3390/healthcare9040450
#+end_quote

#+begin_quote
Karakose, Turgut et al. “Examining the Associations between COVID-19-Related Psychological Distress, Social Media Addiction, COVID-19-Related Burnout, and Depression among School Principals and Teachers through Structural Equation Modeling.” /International journal of environmental research and public health/ vol. 19,4 1951. 10 Feb. 2022, doi:10.3390/ijerph19041951
#+end_quote

#+begin_quote
Çimke, Sevim, and Esin Cerit. "Social media addiction, cyberbullying and cyber victimization of university students." /Archives of psychiatric nursing/ 35.5 (2021): 499-503.
#+end_quote

#+begin_quote
Sagar, Mehmet Enes. "Predictive Role of Cognitive Flexibility and Self-Control on Social Media Addiction in University Students." /International Education Studies/ 14.4 (2021): 1-10.
#+end_quote

#+begin_quote
Kwok, Carrie, et al. “The effects of internet gaming and social media use on physical activity, sleep, quality of life, and academic performance among university students in Hong Kong.” /Asian Journal of Social Health and Behavior/, vol. 4, no. 1, Jan. 2021, pp. 36–44, https://doi.org/10.4103/shb.shb_81_20.
#+end_quote

#+begin_quote
Ostic, Dragana, et al. "Effects of social media use on psychological well-being: a mediated model." /Frontiers in psychology/ 12 (2021): 678766.
#+end_quote

#+begin_quote
Ozimek, Phillip, et al. "Materialism 2.0–More Social Media Addiction and Stress Symptoms, Less Satisfaction with Life." /Less Satisfaction with Life/.
#+end_quote